// Generated by CoffeeScript 1.8.0
(function() {
  var Mpeg1Muxer, child_process, events, util;

  child_process = require('child_process');

  util = require('util');

  events = require('events');

  Mpeg1Muxer = function(options) {
    var self;
    self = this;
    this.rtspTransport = options.rtspTransport;
    this.url = options.url;
    this.bitrate = options.bitrate;
    this.framerate = options.framerate;
    this.args = [
      '-rtsp_transport', this.rtspTransport, // rtsp tranmsport input protocol: ffmpeg.org/ffmpeg-protocols.html#rtsp
      '-i', this.url, // rtsp input source
      '-f', 'mpeg1video', // output video codec: ffmpeg.org/ffmpeg.html#Main-options
      '-b:v', this.bitrate, // output bitrate: ffmpeg.org/ffmpeg.html#Description
      '-r', this.framerate, // output framrate: ffmpeg.org/ffmpeg.html#Video-Options
      'pipe:1'
    ];
    this.stream = child_process.spawn("ffmpeg", this.args, {
      detached: false
    });
    this.inputStreamStarted = true;
    this.stream.stdout.on('data', function(data) {
      return self.emit('mpeg1data', data);
    });
    this.stream.stderr.on('data', function(data) {
      return self.emit('ffmpegError', data);
    });
    return this;
  };

  util.inherits(Mpeg1Muxer, events.EventEmitter);

  module.exports = Mpeg1Muxer;

}).call(this);
